services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        working_dir: /var/www
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
            - /var/www/node_modules
            - /var/www/vendor
        environment:
            - APP_ENV=local
        env_file:
            -   .env
        networks:
            -  backend_network
        depends_on:
            -   db

    db:
      image: postgres:16
      container_name: db
      restart: always
      environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes: 
          - pgdata:/var/lib/postgresql/data
      networks:
          - backend_network
      ports:
          - "5432:5432"

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - backend
        networks:
            - backend_network

networks:
  backend_network:
    driver: bridge

volumes: 
  pgdata: