import type { Metadata } from "next";
import "@/assets/css/global.scss";
import Navigation from "@/widgets/navigation/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <section className="container">
            <Navigation/>
            {children}
        </section>
      </body>
    </html>
  );
}
